name = "me"
workers_dev = true

compatibility_date = "2022-06-30"
account_id = "{{CLOUDFLARE_ACCOUNT_ID}}"

main = "index.js"

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = '{{CLOUDFLARE_BUCKET_NAME}}'
preview_bucket_name = '{{CLOUDFLARE_PREVIEW_BUCKET_NAME}}'

[vars]
GITHUB = "https://github.com/bytemain"
ENVIRONMENT = "dev"


[env.prod]
vars = { ENVIRONMENT = "prod" }
