name = "me"
type = "javascript"
workers_dev = true

compatibility_date = "2022-06-30"
account_id = "{{CLOUDFLARE_ACCOUNT_ID}}"

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = '{{CLOUDFLARE_BUCKET_NAME}}'